#include "class_RecoHit.h"

recoHit::recoHit(int cEvent, int cHitView, int cGenType, int cHitChan, float cHitTime, float cHitSADC, float cHitRMS)
{
  fEvent   = cEvent;
  fHitView = cHitView;
  fGenType = cGenType;
  fHitChan = cHitChan;
  fHitTime = cHitTime;
  fHitSADC = cHitSADC;
  fHitTime = cHitTime;
  fHitRMS  = cHitRMS;
}

int   recoHit::getEvent()  {return fEvent;}
int   recoHit::getHitView(){return fHitView;}
int   recoHit::getGenType(){return fGenType;}
int   recoHit::getHitChan(){return fHitChan;}
float recoHit::getHitTime(){return fHitTime;}
float recoHit::getHitSADC(){return fHitSADC;}
float recoHit::getHitRMS(){return fHitRMS;}

void recoHit::printHit()
{
  std::cout << "Event: " << fEvent << " Plane: " << fHitView << " Generated by: " << fGenType 
            << " On channel: " << fHitChan << " At time: " << fHitTime 
            << " ADCSum: "     << fHitSADC << " RMS: "     << fHitRMS             << std::endl;
  return;
}
